name: Moderazione
version: 1.0.0
main: com.moderation.Moderazione
api-version: '1.21'
author: TuoNome

commands:
  ban:
    permission: moderazione.admin
  tempban:
    permission: moderazione.admin
  ipban:
    permission: moderazione.admin
  tempipban:
    permission: moderazione.admin
  unban:
    permission: moderazione.admin
  mute:
    permission: moderazione.staff
  tempmute:
    permission: moderazione.staff
  unmute:
    permission: moderazione.staff
  warn:
    permission: moderazione.staff
  kick:
    permission: moderazione.staff
  clearchat:
    permission: moderazione.staff
  dupeip:
    permission: moderazione.staff
